spring:
  application:
    name: my-book-service
  zipkin:
    base-url: http://localhost:7882/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7878/eureka/
      
server:
  port: 7880
  